name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Initial_set_up_1
      id: initial_set_up_1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Initial_set_up_1
        setup-command: ''
        command: actions/checkout@v4
        timeout: 10
    - name: Initial_set_up_2
      id: initial_set_up_2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Initial_set_up_2
        setup-command: ''
        command: npm install -g @angular/cli
        timeout: 10
    - name: Initial_set_up_3
      id: initial_set_up_3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Initial_set_up_3
        setup-command: ''
        command: npm install
        timeout: 10
    - name: Initial_set_up_4
      id: initial_set_up_4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Initial_set_up_4
        setup-command: ''
        command: npm install cypress-multi-reporters mocha-junit-reporter --save-dev
        timeout: 10
    - name: Initial_set_up_5
      id: initial_set_up_5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Initial_set_up_5
        setup-command: ''
        command: npm start &
        timeout: 10
    - name: Test_1
      id: test_1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test_1
        setup-command: ''
        command: npx cypress run --spec cypress/e2e/1-view-supplier.cy.ts
        timeout: 10
        max-score: 10
    - name: Test_2
      id: test_2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test_2
        setup-command: ''
        command: npx cypress run --spec cypress/e2e/2-view-supplier-date-validation.cy.ts
        timeout: 10
        max-score: 10
    - name: Test_3
      id: test_3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test_3
        setup-command: ''
        command: npx cypress run --spec cypress/e2e/3-add-supplier-button-validation.cy.ts
        timeout: 10
        max-score: 10
    - name: Test_4
      id: test_4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test_4
        setup-command: ''
        command: npx cypress run --spec cypress/e2e/4-add-supplier-reset.cy.ts
        timeout: 10
        max-score: 10
    - name: Test_5
      id: test_5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test_5
        setup-command: ''
        command: npx cypress run --spec cypress/e2e/5-add-supplier.cy.ts
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INITIAL_SET_UP_1_RESULTS: "${{steps.initial_set_up_1.outputs.result}}"
        INITIAL_SET_UP_2_RESULTS: "${{steps.initial_set_up_2.outputs.result}}"
        INITIAL_SET_UP_3_RESULTS: "${{steps.initial_set_up_3.outputs.result}}"
        INITIAL_SET_UP_4_RESULTS: "${{steps.initial_set_up_4.outputs.result}}"
        INITIAL_SET_UP_5_RESULTS: "${{steps.initial_set_up_5.outputs.result}}"
        TEST_1_RESULTS: "${{steps.test_1.outputs.result}}"
        TEST_2_RESULTS: "${{steps.test_2.outputs.result}}"
        TEST_3_RESULTS: "${{steps.test_3.outputs.result}}"
        TEST_4_RESULTS: "${{steps.test_4.outputs.result}}"
        TEST_5_RESULTS: "${{steps.test_5.outputs.result}}"
      with:
        runners: initial_set_up_1,initial_set_up_2,initial_set_up_3,initial_set_up_4,initial_set_up_5,test_1,test_2,test_3,test_4,test_5
